title: "Assignments 1–3 Analysis"
author: "Yvonne Wang"
format:
  html:
    theme: cosmo
    toc: true

website:
  title: "Analyses"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Assignment 1
        href: a1.qmd
      - text: Assignment 2
        href: ca2.qmd
      - text: Assignment 3
        href: a3.qmd

publish:
  github:
    branch: main     # where your site lives
    folder: docs     # output folder served by Pages