title: "Assignments 1–3 Analysis"
author: "Yvonne Wang"
format:
  html:
    theme: cosmo
    toc: true

website:
  title: "Analyses"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Assignment 1
        href: content/assignment1.qmd
      - text: Assignment 2
        href: content/assignment2.qmd
      - text: Assignment 3
        href: content/assignment3.qmd